CREATE DATABASE HEALTHCARE;
USE DATABASE HEALTHCARE;

CREATE TABLE CAREDATA(
    NAME VARCHAR(25) NOT NULL,
    EMAIL VARCHAR(50),
    PHONE INT,
    APPOINTMENT_DATE DATE,
    DOCTOR VARCHAR(50)
);

 CREATE TABLE BLOOD(
    -> NAME VARCHAR(50),
    -> AGE VARCHAR(10),
    -> BLOOD VARCHAR(10),
    -> EMAIL VARCHAR(50),
    -> CONTACT VARCHAR(30),
    -> AVAILABILITY VARCHAR(20)
    -> );